### ISSUE TITLE
images exclusive to a site

### ISSUE THREAD

**Issue by 99spooner** [DontTalkToMeThx/BooruSlideshow#16]
i dont know if this is even possible but its a thought i had is some way like a button or something to make it so that you only view images that are exclusive to that one site (for whatever reason), for example if an image is on rule 34 but is also on e621  it wont show up but if the image is exclusively on rule 34 it would show up

i have no idea if this is possible but its just something i wanted to throw out there

(also when i mean exclusive i mean to the list that booru slideshow has, im pretty sure that little to no artist have put there art up exclusively on these sites)

**Comment by DontTalkToMeThx** [comment]
Unless I could search for exact md5 tags on all sites without loading the pictures, it'd be impossible. Also, this would make 10 times more requests taking up a lot of extra bandwidth. Currently I won't be looking into this feature, also I updated the readme. I won't be working on the chrome extension from this point forward unless something breaks because having both development streams makes it extremely difficult to add any new features to both.
